buildscript {
    repositories {maven {url = 'https://maven.fabricmc.net/'}}
    apply from: "versions.gradle"
    def (loomGroupId, loomArtifactId, loomVersion, loomBaseId) = getFabricLoom(project.minecraft_version)
    def minecraftRelease = getMinecraftReleaseVersion(minecraft_version)
    def (fabricLoaderVersion, minFabricLoaderVersion, fabricApiVersion) = getLatestFabricVersions(minecraftRelease)
    def (minMinecraftVersionExcl, maxMinecraftVersionExcl) = getMinecraftVersionExclRange(minecraft_version_min_excl, minecraft_version_max_excl)
    def (javaVersionNum, javaVersionEnum) = getJavaVersions(minecraftRelease)
    dependencies {
        classpath "$loomGroupId:$loomArtifactId:$loomVersion"
    }
    ext {
        ext.loomPluginBaseId = loomBaseId
        ext.minecraftRelease = minecraftRelease
        ext.fabricLoaderVersion = fabricLoaderVersion
        ext.minFabricLoaderVersion = minFabricLoaderVersion
        ext.fabricApiVersion = fabricApiVersion
        ext.minMinecraftVersionExcl = minMinecraftVersionExcl
        ext.maxMinecraftVersionExcl = maxMinecraftVersionExcl
        ext.javaVersionNum = javaVersionNum
        ext.javaVersionEnum = javaVersionEnum
    }
}
plugins {
    id 'dev.isxander.mtk.modrepos'
}

apply plugin: "${loomPluginBaseId}"
apply from: "versions.gradle"
apply plugin: "dev.isxander.mtk.modrepos"

def getMinecraftVersionName(){
    String key = 'minecraft_version_name'
    if (project.hasProperty(key)) {String value = project.getProperties().get(key); return !value.isEmpty() ? value : project.minecraft_version}
    else {return project.minecraft_version}
}
version = "${mod_version}+${getMinecraftVersionName()}-Fabric"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
    modrinthApi.exclusive()
}

loom {
    accessWidenerPath = file("src/main/resources/mstv-base.accesswidener")
    log4jConfigs.from(file("log4j.xml"))
}

dependencies {
    implementation 'org.apache.commons:commons-text:1.12.0'
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabricLoaderVersion}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabricApiVersion}"

	// MStV+ Villager Trades
	compileOnly "maven.modrinth:more-weapon-variants:${project.m_weapon_v_version_id}"
	compileOnly "maven.modrinth:more-tool-variants:${project.m_tool_v_version_id}"
	compileOnly "maven.modrinth:more-frame-variants:${project.m_frame_v_version_id}"
	compileOnly "maven.modrinth:more-fishing-rod-variants:${project.m_fishing_rod_v_version_id}"
		// Nemo's Campfires
		compileOnly "maven.modrinth:nemos-campfires:${project.nemos_campfires_version_id}"
		// More Fletching Tables
		compileOnly "maven.modrinth:more-fletching-tables:${project.m_fletching_t_version_id}"
		// More Shield Variants
		compileOnly "maven.modrinth:more-shield-variants:${project.m_shield_v_version_id}"
			// More Extra Shield Variants
			compileOnly "maven.modrinth:more-extra-shield-variants:${project.m_extra_shield_v_version_id}"
		// More Bed Variants
		compileOnly "maven.modrinth:more-bed-variants:${project.m_bed_v_version_id}"
		// More Bookshelf Variants
		compileOnly "maven.modrinth:more-bookshelf-variants-lieonlion:${project.m_bookshelf_v_lol_version_id}"

	// MStV+ Villager Trades (Testing)
	/**/
	//localRuntime "maven.modrinth:more-weapon-variants:${project.m_weapon_v_version_id}"
	//localRuntime "maven.modrinth:more-tool-variants:${project.m_tool_v_version_id}"
	//localRuntime "maven.modrinth:more-frame-variants:${project.m_frame_v_version_id}"
	//localRuntime "maven.modrinth:more-fishing-rod-variants:${project.m_fishing_rod_v_version_id}"
		// nemosCampfireV
		//localRuntime "maven.modrinth:nemos-campfires:${project.nemos_campfires_version_id}"
		// More Fletching Tables
		//localRuntime "maven.modrinth:more-fletching-tables:${project.m_fletching_t_version_id}"
		// More Shield Variants
		//localRuntime "maven.modrinth:more-shield-variants:${project.m_shield_v_version_id}"
		// More Bed Variants
		//localRuntime "maven.modrinth:more-bed-variants:${project.m_bed_v_version_id}"
		// More Bookshelf Variants
		//localRuntime "maven.modrinth:more-bookshelf-variants-lieonlion:${project.m_bookshelf_v_lol_version_id}"
		//localRuntime "maven.modrinth:quad:${project.quad_version_id}"
    // Extra Testing (LieOnLion) 1.21.11
    //localRuntime "maven.modrinth:more-chest-variants-lieonlion:DbsvowYO"
    //localRuntime "maven.modrinth:more-crafting-tables-lieonlion:XsN6Ellv"

}

def replaceProperties = [
        mod_id: mod_id, mod_name: mod_name, mod_description: mod_description, mod_license: mod_license,
        mod_version: mod_version,
        minFabricLoaderVersion: minFabricLoaderVersion,
        minMinecraftVersionExcl: minMinecraftVersionExcl, maxMinecraftVersionExcl: maxMinecraftVersionExcl, javaVersion: javaVersionNum
]
println "===\nExpanding the following values into fabric.mod.json and *.mixins.json:\n${replaceProperties.collect { k, v -> "  ${k}: ${v}" }.join('\n')}\n==="

processResources {

    filesMatching("fabric.mod.json") {
        expand replaceProperties
    }
    filesMatching("*.mixins.json") {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = javaVersionNum
}

java {
    sourceCompatibility = javaVersionEnum
    targetCompatibility = javaVersionEnum
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}"}
    }
}