# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx6G
org.gradle.parallel = true

# Minecraft Properties
minecraft_version = 1.21.1
minecraft_version_supported = [1.21,1.21.1]
minecraft_version_lower = 1.20.6
minecraft_version_upper = 1.21.4

# File Name
minecraft_version_name = 1.21(.1)
archives_base_name = MoreStickVariants

# Mod Properties
mod_id = mstv-base
mod_name = More Stick Variants (MStV)
mod_name_short = More Stick Variants
mod_description = This mod adds more variants of the Stick Item. It is a base mod to help craft other variants using recipes with sticks as ingredients.
mod_version = 1.4.15
mod_license = MIT
maven_group = de.pnku

# MStV+ Villager Trades
mweaponv_version_id = SKsJOqNV
mtoolv_version_id = ylQrrxLY
mframev_version_id = Rt10dbNS
mfrodv_version_id = RbBBeWgE
nemoscampfirev_version_id = aWfEfKQY
mfletchingtablev_version_id = n3ECpzTv
mshieldv_version_id = LQcsnGUJ
mxshieldv_version_id = PMq5QzDy
mbedv_version_id = cpzmkA2R
mbookshelfv_version_id = hgLqbkLp
quad_version_id = 5SqDjW5O