# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx6G
org.gradle.parallel = true

# Minecraft Properties
minecraft_version = 1.21.4
minecraft_version_supported = [1.21.4]
minecraft_version_min_excl = 1.21.1
minecraft_version_max_excl = 1.21.5

# File Name
minecraft_version_name = 1.21.4
archives_base_name = MoreStickVariants

# Mod Properties
mod_id = mstv-base
mod_name = More Stick Variants (MStV)
mod_name_short = More Stick Variants
mod_description = This mod adds more variants of the Stick Item. It is a base mod to help craft other variants using recipes with sticks as ingredients.
mod_version = 1.4.20
mod_license = CC-BY-NC-SA-4.0
maven_group = de.pnku

# MStV+ Villager Trades
m_weapon_v_version_id = gEC2q3sb
m_tool_v_version_id = 1iTLZMt9
m_frame_v_version_id = MvO4172j
m_fishing_rod_v_version_id = QoktJ9FU
nemos_campfires_version_id = Cuu3lO2x
m_fletching_t_version_id = ctB6opvM
m_shield_v_version_id = m7fwTlDM
m_extra_shield_v_version_id = PMq5QzDy
m_bed_v_version_id = g2RuCc3J
m_bookshelf_v_lol_version_id = V57g2S8g
quad_version_id = 4oqSVhwd