# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx6G
org.gradle.parallel = true

# Fabric Properties
minecraft_version = 1.21.4
loader_version = 0.16.10
fapi_version = 0.119.2+1.21.4

# Mod Properties
mod_id = mstv-base
mod_name = More Stick Variants (MStV)
mod_description = This mod adds more variants of the Stick Item. It is a base mod to help craft other variants using recipes with sticks as ingredients.
mod_version = 1.4.4
mod_license = MIT
maven_group = de.pnku
archives_base_name = MoreStickVariants

# MStV+ Villager Trades
mweaponv_version_id = 7byiDEaw
mtoolv_version_id = v6OMvRyJ
mframev_version_id = SFbIq4Gk
mfrodv_version_id = QoktJ9FU
nemoscampfirev_version_id = Cuu3lO2x
mfletchingtablev_version_id = xGc0GY9O
mshieldv_version_id = g436xuon
mbedv_version_id = B2UvMnhS
mbookshelfv_version_id = lxlBBhP3
quad_version_id = 4oqSVhwd