pluginManagement {
	apply from: "versions.gradle"

	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}

	resolutionStrategy {
		eachPlugin {
			if (requested.id.id == "fabric-loom" || requested.id.id == "net.fabricmc.fabric-loom-remap.gradle.plugin") {
				def (groupId, artifactId, version) = getFabricLoom(settings.minecraft_version)
				useModule "$groupId:$artifactId:$version"
			}
		}
	}

	plugins {
		id 'dev.isxander.mtk.modrepos' version '0.1.2'
	}
}