blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.com/invite/sA42pp6cuX
    about: Join Discord server
  - name: E-Mail
    url: mailto:contact@pnku.de
    about: Feel free to send me an e-mail directly.
